# .travis.yml
sudo: false

language: node_js

node_js:
  - '0.12'
  - '4.0.0'
  - '4.1.0'

env:
  - NODE_ENV=test

before_script:
  - npm install
  - npm install istanbul -g

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
  code_climate:
    repo_token:
      secure: ""
