# .travis.yml
sudo: false

language: node_js

node_js:
  - '0.12'
  - '4.0.0'
  - '4.1.0'

env:
  - NODE_ENV=test

before_script:
  - npm install
  - npm install istanbul -g

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
  code_climate:
    repo_token:
      secure: "GmZaWL+OJnTnU+2qKTAu3rajeZhYLGq1jeBHPHhq/GTpefo5GGlrWb6ZcEw0FkOminIjisBa537Ggw1tSOgWKhZJnzpUhrp50qWZSYzQPNzkjVsMKPT69PjlRLNK34ed5ONG5f6iE2r7gs/XvEBiPp+zA0fMO/quOsbyJxcD20m7a46/TgE5/Ne9WE9TYeFG8KwxWFOYN9vUP+2USE0oBMgLYPsVSHCtHAyx/SpvbVkyjbgoyeYxYEDqO+InMdvD3AFb/UB5ptGkWd4+CWLtBGtG+zi1OxYIGzNKXxb8WTzfAf+/UzOlJnM+0IDfy7RPgLymr4pnkKvp5So0I4mP1n5ecuIMH7/+TAGrG/YbDGGtGjECulX1oF/xUcJQzvjlMzHBmnFysJ8rAf2EeMxucOr5T/aZqvQDQ2SXxXnFT193IAg8wtPEAORGDq7nQKJsaCH8cZW66W9MyK5SY3Qz2zRraX6NFd6TDpnw/pyIu0T/LRTEuUNxW7oacidiOTOtkS1uJIiqDLMpGnPR8LYNSsunow08XHzs0e8DJLA5SXd90a6b5P7+GDxUf10sI+HPluQTHgVjVTC+LPyyJI8d//FVsSPF0FhortSZyPFRoU2qdrlUOISrKrMye7QzIxc2W/RH7lzSFME7SaD5WpqR6NfxhLkmKAi8nreehlqLISg="
